// ============================================================
// ============================================================

import 'sos_map_screen.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart'; // generated by: flutterfire configure
import 'package:geolocator/geolocator.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:geocoding/geocoding.dart';

// ============================================================
// ENTRY POINT
// ============================================================
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // ← THIS LINE WAS MISSING
  );

  runApp(const DonorFinderApp());
}

// ============================================================
// DATA MODEL — SOSRequest
// ============================================================
class SOSRequest {
  final String id;
  final String name;
  final String bloodType;
  final GeoPoint location;
  final Timestamp timestamp;
  final String address;

  const SOSRequest({
    required this.id,
    required this.name,
    required this.bloodType,
    required this.location,
    required this.timestamp,
    this.address = "Locating...",
  });

  factory SOSRequest.fromMap(String id, Map<String, dynamic> map) {
    return SOSRequest(
      id: id,
      name: map['patientName'] as String? ?? map['name'] as String? ?? 'Urgent Request',
      bloodType: map['bloodType'] as String? ?? 'A+',
      location: map['location'] as GeoPoint? ?? const GeoPoint(0, 0),
      timestamp: map['timestamp'] as Timestamp? ?? Timestamp.now(),
      address: map['address'] as String? ?? "Location pending...",
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'bloodType': bloodType,
      'location': location,
      'timestamp': timestamp,
    };
  }
}

// ============================================================
// FIRESTORE SERVICE
// ============================================================
Future<String> submitSOSRequest({
  required String name,
  required String bloodType,
  required GeoPoint location,
  required String address,
  String phoneNumber = "9876543210",
}) async {
  final docRef = await FirebaseFirestore.instance
      .collection('emergencies')
      .add({
    'patientName': name,
    'bloodType': bloodType,
    'location': location,
    'address': address,
    'phoneNumber': phoneNumber,
    'timestamp': FieldValue.serverTimestamp(),
    'status': 'active',
  });
  return docRef.id;
}

// ============================================================
// APP ROOT
// ============================================================
class DonorFinderApp extends StatelessWidget {
  const DonorFinderApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Local Donor Finder',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFC62828),
          brightness: Brightness.light,
          primary: const Color(0xFFC62828),
          onPrimary: Colors.white,
          surface: const Color(0xFFFFF8F8),
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFFC62828),
          foregroundColor: Colors.white,
          elevation: 0,
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFFC62828),
            foregroundColor: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(16),
            ),
          ),
        ),
        scaffoldBackgroundColor: const Color(0xFFFFF8F8),
      ),
      home: const MainShell(),
    );
  }
}

// ============================================================
// MAIN SHELL — BottomNavigationBar
// ============================================================
class MainShell extends StatefulWidget {
  const MainShell({super.key});

  @override
  State<MainShell> createState() => _MainShellState();
}

class _MainShellState extends State<MainShell> {
  int _selectedIndex = 0;

  static const List<Widget> _pages = [
    HomeScreen(),
    SOSMapScreen(),
    PostRequestScreen(),
    ProfileScreen(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _pages[_selectedIndex],
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _selectedIndex,
        onTap: (i) => setState(() => _selectedIndex = i),
        selectedItemColor: const Color(0xFFC62828),
        unselectedItemColor: Colors.grey[500],
        backgroundColor: Colors.white,
        type: BottomNavigationBarType.fixed,
        elevation: 8,
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.home_outlined),
            activeIcon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.map_outlined),
            activeIcon: Icon(Icons.map),
            label: 'Map',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.edit_note_outlined),
            activeIcon: Icon(Icons.edit_note),
            label: 'Post',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.person_outline),
            activeIcon: Icon(Icons.person),
            label: 'Profile',
          ),
        ],
      ),
    );
  }
}

// ============================================================
// SCREEN 1 — HomeScreen
// ============================================================
class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Donor Finder'),
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(24),
          child: Padding(
            padding: const EdgeInsets.only(left: 16, bottom: 10),
            child: Align(
              alignment: Alignment.centerLeft,
              child: Text(
                'Find help near you, instantly',
                style: Theme.of(context)
                    .textTheme
                    .bodySmall
                    ?.copyWith(color: Colors.white70),
              ),
            ),
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _WelcomeCard(),
            const SizedBox(height: 20),
            _EmergencyButton(),
            const SizedBox(height: 28),
            Text('Recent SOS requests', style: _sectionLabelStyle()),
            const SizedBox(height: 10),
            StreamBuilder<QuerySnapshot>(
              stream: FirebaseFirestore.instance
                  .collection('emergencies')
                  .where('status', isEqualTo: 'active')
                  .orderBy('timestamp', descending: true)
                  .limit(10)
                  .snapshots(),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Center(
                    child: Padding(
                      padding: EdgeInsets.all(24),
                      child: CircularProgressIndicator(
                          color: Color(0xFFC62828)),
                    ),
                  );
                }
                if (snapshot.hasError) {
                  return Center(
                    child: Text('Error: ${snapshot.error}',
                        style: const TextStyle(color: Colors.red)),
                  );
                }
                final docs = snapshot.data?.docs ?? [];
                if (docs.isEmpty) return const _EmptyRequestsCard();
                return Column(
                  children: docs.map((doc) {
                    final request = SOSRequest.fromMap(
                        doc.id, doc.data() as Map<String, dynamic>);
                    return _SOSRequestCard(request: request);
                  }).toList(),
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}

class _EmptyRequestsCard extends StatelessWidget {
  const _EmptyRequestsCard();

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: const Border.fromBorderSide(
          BorderSide(color: Color(0xFFF5C4C4), width: 0.5),
        ),
      ),
      child: Column(
        children: [
          Icon(Icons.check_circle_outline, color: Colors.green[400], size: 36),
          const SizedBox(height: 8),
          Text(
          'No urgent requests nearby',
          style: TextStyle(color: Colors.grey[600], fontSize: 16),
        ),
        Text(
          'Check back later or share the app!',
          style: TextStyle(color: Colors.grey[400], fontSize: 12),
        ),
        ],
      ),
    );
  }
}

class _SOSRequestCard extends StatelessWidget {
  final SOSRequest request;
  const _SOSRequestCard({required this.request});

  @override
  Widget build(BuildContext context) {
    final time = request.timestamp.toDate();
    final timeStr =
        '${time.hour.toString().padLeft(2, '0')}:${time.minute.toString().padLeft(2, '0')}';

    return Card(
      elevation: 0,
      color: Colors.white,
      margin: const EdgeInsets.only(bottom: 10),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(14),
        side: const BorderSide(color: Color(0xFFF5C4C4), width: 0.5),
      ),
      child: Padding(
        padding: const EdgeInsets.all(14),
        child: Row(
          children: [
            CircleAvatar(
              backgroundColor: const Color(0xFFFFEBEE),
              radius: 22,
              child: Text(request.bloodType,
                  style: const TextStyle(
                    color: Color(0xFFC62828),
                    fontWeight: FontWeight.w700,
                    fontSize: 12,
                  )),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(request.name,
                      style: const TextStyle(
                          fontWeight: FontWeight.bold, fontSize: 15)), // Increased bold for visibility
                  const SizedBox(height: 2),
                  // Display dynamic address + timestamp
                  Text('${request.address} • $timeStr',
                      style: TextStyle(
                          fontSize: 12, color: Colors.grey[600])),
                ],
              ),
            ),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
              decoration: BoxDecoration(
                color: const Color(0xFFFFEBEE),
                borderRadius: BorderRadius.circular(20),
              ),
              child: const Text('ACTIVE',
                  style: TextStyle(
                    color: Color(0xFFC62828),
                    fontSize: 10,
                    fontWeight: FontWeight.w700,
                    letterSpacing: 0.5,
                  )),
            ),
          ],
        ),
      ),
    );
  }
}

class _WelcomeCard extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 0,
      color: Colors.white,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
        side: const BorderSide(color: Color(0xFFF5C4C4), width: 0.5),
      ),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Row(
          children: [
            const CircleAvatar(
              radius: 24,
              backgroundColor: Color(0xFFFFEBEE),
              child: Text('🩸', style: TextStyle(fontSize: 20)),
            ),
            const SizedBox(width: 12),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('Good morning, Arjun',
                    style: TextStyle(
                        fontWeight: FontWeight.w600, fontSize: 16)),
                const SizedBox(height: 2),
                // This could be made dynamic later with the user's actual location
                Text('Hyderabad • Blood type A+',
                    style: TextStyle(
                        fontSize: 13, color: Colors.grey[600])),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
class _EmergencyButton extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: double.infinity,
      height: 130,
      child: ElevatedButton(
        onPressed: () {
          print("Button Clicked!"); // debug check

          // Show message
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text("Opening SOS form..."),
            ),
          );

          // Open bottom sheet
          _showSOSBottomSheet(context);
        },
        style: ElevatedButton.styleFrom(
          backgroundColor: const Color(0xFFC62828),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20),
          ),
        ),
        child: const Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.emergency, size: 36, color: Colors.white),
            SizedBox(height: 8),
            Text(
              'Request Emergency Help',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.w600,
                color: Colors.white,
              ),
            ),
            SizedBox(height: 4),
            Text(
              'Tap to alert nearby donors',
              style: TextStyle(fontSize: 12, color: Colors.white70),
            ),
          ],
        ),
      ),
    );
  }
}
// ============================================================
// SOS BOTTOM SHEET
// ============================================================
void _showSOSBottomSheet(BuildContext context) {
  showModalBottomSheet(
    context: context,
    isScrollControlled: true,
    backgroundColor: Colors.transparent,
    builder: (_) => const _SOSBottomSheet(),
  );
}

class _SOSBottomSheet extends StatefulWidget {
  const _SOSBottomSheet();

  @override
  State<_SOSBottomSheet> createState() => _SOSBottomSheetState();
}

class _SOSBottomSheetState extends State<_SOSBottomSheet> {
  final _nameController = TextEditingController();
  String _selectedBloodType = 'A+';
  bool _isSubmitting = false;

  static const _bloodTypes = [
    'A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'
  ];

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    final name = _nameController.text.trim();

    if (name.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter your name')),
      );
      return;
    }

    setState(() => _isSubmitting = true);
    bool _success = false;

    try {
      // Check permission (don't request yet — check first)
      LocationPermission permission = await Geolocator.checkPermission();

      if (permission == LocationPermission.denied) {
        permission = await Geolocator.requestPermission();
      }

      // Step 2: Handle denied states — show message, set flag, bail
      if (permission == LocationPermission.denied ||
          permission == LocationPermission.deniedForever) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(
                permission == LocationPermission.deniedForever
                    ? 'Location permanently denied. Enable it in Settings.'
                    : 'Location permission is required to post an SOS.',
              ),
            ),
          );
        }
        return;
      }

      // Step 3: Get position
      final Position position = await Geolocator.getCurrentPosition(
        locationSettings: const LocationSettings(
          accuracy: LocationAccuracy.high,
        ),
      );

      debugPrint('GPS → LAT: ${position.latitude}, LNG: ${position.longitude}');

      final location = GeoPoint(position.latitude, position.longitude);
      await submitSOSRequest(
        name: name,
        bloodType: _selectedBloodType,
        location: location,
        address: "Warangal", // Updated text
        phoneNumber: "9876543210",
      );

      _success = true; // only set true after successful Firestore write

    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to post SOS: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      // Always stop the spinner
      if (mounted) setState(() => _isSubmitting = false);
      if (_success && mounted) {
        Navigator.of(context).pop();
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Row(
                children: [
                  Icon(Icons.check_circle, color: Colors.white),
                  SizedBox(width: 10),
                  Text('SOS Posted Successfully!'),
                ],
              ),
              backgroundColor: Color(0xFFC62828),
              behavior: SnackBarBehavior.floating,
            ),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final bottomInset = MediaQuery.of(context).viewInsets.bottom;

    return Container(
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      padding: EdgeInsets.fromLTRB(24, 20, 24, 24 + bottomInset),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Center(
            child: Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: Colors.grey[300],
                borderRadius: BorderRadius.circular(4),
              ),
            ),
          ),
          const SizedBox(height: 20),
          const Text('Post SOS Request',
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600)),
          const SizedBox(height: 4),
          Text('Nearby donors will be notified immediately.',
              style: TextStyle(fontSize: 13, color: Colors.grey[600])),
          const SizedBox(height: 24),

          const Text('Your name',
              style: TextStyle(fontSize: 13, fontWeight: FontWeight.w500)),
          const SizedBox(height: 8),
          TextField(
            controller: _nameController,
            textCapitalization: TextCapitalization.words,
            decoration: InputDecoration(
              hintText: 'e.g. Manasa',
              prefixIcon: const Icon(Icons.person_outline),
              filled: true,
              fillColor: const Color(0xFFFFF8F8),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Color(0xFFF5C4C4)),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Color(0xFFF5C4C4)),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide:
                    const BorderSide(color: Color(0xFFC62828), width: 1.5),
              ),
            ),
          ),
          const SizedBox(height: 18),

          const Text('Blood type needed',
              style: TextStyle(fontSize: 13, fontWeight: FontWeight.w500)),
          const SizedBox(height: 8),
          DropdownButtonFormField<String>(
            value: _selectedBloodType,
            decoration: InputDecoration(
              prefixIcon: const Icon(Icons.water_drop_outlined,
                  color: Color(0xFFC62828)),
              filled: true,
              fillColor: const Color(0xFFFFF8F8),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Color(0xFFF5C4C4)),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Color(0xFFF5C4C4)),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide:
                    const BorderSide(color: Color(0xFFC62828), width: 1.5),
              ),
            ),
            items: _bloodTypes
                .map((bt) => DropdownMenuItem(value: bt, child: Text(bt)))
                .toList(),
            onChanged: (val) {
              if (val != null) setState(() => _selectedBloodType = val);
            },
          ),
          const SizedBox(height: 28),

          SizedBox(
            width: double.infinity,
            height: 52,
            child: ElevatedButton(
              onPressed: _isSubmitting ? null : _submit,
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFFC62828),
                disabledBackgroundColor: Colors.red[200],
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(14)),
              ),
              child: _isSubmitting
                  ? const SizedBox(
                      width: 22,
                      height: 22,
                      child: CircularProgressIndicator(
                          color: Colors.white, strokeWidth: 2.5),
                    )
                  : const Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(Icons.emergency, size: 20),
                        SizedBox(width: 8),
                        Text('Submit SOS',
                            style: TextStyle(
                                fontSize: 16, fontWeight: FontWeight.w600)),
                      ],
                    ),
            ),
          ),
        ],
      ),
    );
  }
}

// ============================================================
// SCREEN 2 — PostRequestScreen
// ============================================================
class PostRequestScreen extends StatefulWidget {
  const PostRequestScreen({super.key});

  @override
  State<PostRequestScreen> createState() => _PostRequestScreenState();
}

class _PostRequestScreenState extends State<PostRequestScreen> {
  // 1. ADDED: nameController and phoneController
  final TextEditingController nameController = TextEditingController();
  final TextEditingController hospitalController = TextEditingController();
  final TextEditingController unitsController = TextEditingController();
  final TextEditingController phoneController = TextEditingController(); // Useful for 'I Can Help' button

  String selectedBloodType = 'A+';
  final List<String> bloodTypes = ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'];

  Future<GeoPoint?> getCoordinatesFromAddress(String address) async {
    try {
      String searchPath = "$address, Warangal, Telangana";
      List<Location> locations = await locationFromAddress(searchPath);
      if (locations.isNotEmpty) {
        return GeoPoint(locations.first.latitude, locations.first.longitude);
      }
    } catch (e) {
      debugPrint("Error finding location: $e");
    }
    return null;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Post a Request')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // 2. ADDED: Patient Name Input Field
            const Text('Patient Name', style: TextStyle(fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            TextField(
              controller: nameController,
              decoration: const InputDecoration(
                hintText: 'Enter full name',
                prefixIcon: Icon(Icons.person),
                border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12))),
              ),
            ),
            
            const SizedBox(height: 16),
            const Text('Blood type needed', style: TextStyle(fontWeight: FontWeight.bold)),
            const SizedBox(height: 12),
            Wrap(
              spacing: 8.0,
              runSpacing: 8.0,
              children: bloodTypes.map((type) {
                bool isSelected = selectedBloodType == type;
                return GestureDetector(
                  onTap: () => setState(() => selectedBloodType = type),
                  child: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                    decoration: BoxDecoration(
                      color: isSelected ? const Color(0xFFC62828) : Colors.red[50],
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(color: isSelected ? Colors.transparent : Colors.red.shade100),
                    ),
                    child: Text(
                      type,
                      style: TextStyle(
                        color: isSelected ? Colors.white : Colors.red[900],
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                );
              }).toList(),
            ),

            const SizedBox(height: 20),
            const Text('Hospital / location', style: TextStyle(fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            TextField(
              controller: hospitalController,
              decoration: const InputDecoration(
                hintText: 'e.g. MGM Hospital, Warangal',
                prefixIcon: Icon(Icons.local_hospital),
                border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12))),
              ),
            ),

            const SizedBox(height: 16),
            const Text('Units required', style: TextStyle(fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            TextField(
              controller: unitsController,
              keyboardType: TextInputType.number,
              decoration: const InputDecoration(
                hintText: 'e.g. 2',
                prefixIcon: Icon(Icons.water_drop),
                border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12))),
              ),
            ),

            const SizedBox(height: 16),
            // 3. ADDED: Phone Number field (Critical for the "I Can Help" feature)
            const Text('Contact Number', style: TextStyle(fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            TextField(
              controller: phoneController,
              keyboardType: TextInputType.phone,
              decoration: const InputDecoration(
                hintText: 'Enter mobile number',
                prefixIcon: Icon(Icons.phone),
                border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12))),
              ),
            ),

            const SizedBox(height: 28),
            SizedBox(
              width: double.infinity,
              height: 52,
              child: ElevatedButton(
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFFC62828),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                ),
                onPressed: () async {
                  // Basic Validation
                  if (hospitalController.text.isEmpty || nameController.text.isEmpty || phoneController.text.isEmpty) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(content: Text("Please fill all fields")),
                    );
                    return;
                  }

                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text("Processing request...")),
                  );

                  try {
                    GeoPoint? location = await getCoordinatesFromAddress(hospitalController.text);

                    if (location == null) {
                      if (!mounted) return;
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(content: Text("Location not found.")),
                      );
                      return;
                    }

                    // 4. MODIFIED: Saving the REAL name and phone from controllers
                    await FirebaseFirestore.instance.collection('emergencies').add({
                      'patientName': nameController.text.trim(), // Replaces "Arjun Kumar"
                      'bloodType': selectedBloodType,
                      'location': location,
                      'timestamp': FieldValue.serverTimestamp(),
                      'address': hospitalController.text,
                      'status': 'active',
                      'hospitalName': hospitalController.text.trim(),
                      'units': unitsController.text.trim(),
                      'phone': phoneController.text.trim(), // Added phone
                    }).timeout(const Duration(seconds: 10));

                    if (!mounted) return;

                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(content: Text("Request Posted Successfully!")),
                    );

                    // 5. CLEAR FIELDS: Now includes name and phone
                    nameController.clear();
                    hospitalController.clear();
                    unitsController.clear();
                    phoneController.clear();

                  } catch (e) {
                    debugPrint("CRITICAL ERROR: $e");
                    if (!mounted) return;
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(content: Text("Error: ${e.toString()}")),
                    );
                  }
                },
                child: const Text('Post Request', style: TextStyle(color: Colors.white, fontSize: 16)),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _BloodTypeSelector extends StatefulWidget {
  @override
  State<_BloodTypeSelector> createState() => _BloodTypeSelectorState();
}
class _BloodTypeSelectorState extends State<_BloodTypeSelector> {
  String _selected = 'A+';
  final _types = ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'];

  @override
  Widget build(BuildContext context) {
    return Wrap(
      spacing: 8,
      runSpacing: 8,
      children: _types
          .map((t) => ChoiceChip(
                label: Text(t),
                selected: _selected == t,
                onSelected: (_) => setState(() => _selected = t),
                selectedColor: const Color(0xFFC62828),
                labelStyle: TextStyle(
                  color: _selected == t
                      ? Colors.white
                      : const Color(0xFFC62828),
                  fontWeight: FontWeight.w500,
                ),
                backgroundColor: const Color(0xFFFFEBEE),
                side: BorderSide.none,
              ))
          .toList(),
    );
  }
}

// ============================================================
// SCREEN 3 — ProfileScreen
// ============================================================
class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('My Profile')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          children: [
            const SizedBox(height: 12),
            const CircleAvatar(
              radius: 44,
              backgroundColor: Color(0xFFFFEBEE),
              child: Text('🩸', style: TextStyle(fontSize: 40)),
            ),
            const SizedBox(height: 12),
            const Text('Arjun Kumar',
                style: TextStyle(
                    fontSize: 20, fontWeight: FontWeight.w600)),
            const SizedBox(height: 4),
            Text('arjun@example.com',
                style: TextStyle(fontSize: 13, color: Colors.grey[600])),
            const SizedBox(height: 24),
            _ProfileInfoRow(label: 'Blood Type', value: 'A+'),
            _ProfileInfoRow(label: 'City', value: 'Hyderabad'),
            _ProfileInfoRow(label: 'Total donations', value: '3'),
            _ProfileInfoRow(label: 'Last donated', value: '12 Jan 2026'),
            const SizedBox(height: 28),
            SizedBox(
              width: double.infinity,
              height: 50,
              child: OutlinedButton.icon(
                icon: const Icon(Icons.logout, size: 18),
                label: const Text('Sign Out'),
                style: OutlinedButton.styleFrom(
                  foregroundColor: const Color(0xFFC62828),
                  side: const BorderSide(color: Color(0xFFC62828)),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12)),
                ),
                onPressed: () {
                  // TODO: FirebaseAuth.instance.signOut()
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _ProfileInfoRow extends StatelessWidget {
  final String label;
  final String value;
  const _ProfileInfoRow({required this.label, required this.value});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 10),
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: const Border.fromBorderSide(
            BorderSide(color: Color(0xFFF5C4C4), width: 0.5)),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label,
              style: TextStyle(fontSize: 14, color: Colors.grey[700])),
          Text(value,
              style: const TextStyle(
                  fontSize: 14, fontWeight: FontWeight.w500)),
        ],
      ),
    );
  }
}

TextStyle _sectionLabelStyle() => const TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w500,
      color: Colors.grey,
      letterSpacing: 0.5,
    );
