// ============================================================
// LOCAL DONOR FINDER — main.dart (Firebase Edition)
// Google Solution Challenge 2026
// ============================================================
//
// ── SETUP CHECKLIST (do these before running) ────────────────
//
//  1. pubspec.yaml — add these under `dependencies:`:
//
//       firebase_core: ^4.6.0
//       cloud_firestore: ^6.2.0
//       geolocator: ^13.0.2        # for real GPS later
//
//     Then run:  flutter pub get
//
//  2. FlutterFire CLI — run in your project root:
//
//       dart pub global activate flutterfire_cli
//       flutterfire configure
//
//     This generates `lib/firebase_options.dart` automatically.
//     The import below (line ~30) points to that generated file.
//     DO NOT hand-write firebase_options.dart — always let the
//     CLI generate it so it stays in sync with your project.
//
//  3. Android: confirm `android/build.gradle` has Google Services
//     plugin (the CLI handles this automatically).
//
// ─────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

// ▼ This file is AUTO-GENERATED by `flutterfire configure`.
//   It lives at lib/firebase_options.dart in your project.
//   If you haven't run the CLI yet, comment this line out
//   and replace `options: DefaultFirebaseOptions.currentPlatform`
//   in main() with just `options: null` temporarily.
import 'firebase_options.dart';

// ============================================================
// ENTRY POINT — async to await Firebase initialization
// ============================================================
void main() async {
  // Must be called before any async work in main()
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the options generated by FlutterFire CLI.
  // DefaultFirebaseOptions.currentPlatform selects the right config
  // for Android, iOS, Web, etc. automatically at runtime.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const DonorFinderApp());
}

// ============================================================
// DATA MODEL — SOSRequest
// Represents a single emergency request stored in Firestore.
// Collection path: `emergencies/{id}`
// ============================================================
class SOSRequest {
  final String id;           // Firestore document ID (set after write)
  final String name;         // Requester's display name
  final String bloodType;    // e.g. "A+", "O-"
  final GeoPoint location;   // lat/lng stored as Firestore GeoPoint
  final Timestamp timestamp; // Server-side creation time

  const SOSRequest({
    required this.id,
    required this.name,
    required this.bloodType,
    required this.location,
    required this.timestamp,
  });

  // ── Firestore → Dart ──────────────────────────────────────
  // Called when reading a document snapshot from Firestore.
  factory SOSRequest.fromMap(String id, Map<String, dynamic> map) {
    return SOSRequest(
      id: id,
      name: map['name'] as String? ?? '',
      bloodType: map['bloodType'] as String? ?? 'A+',
      location: map['location'] as GeoPoint? ?? const GeoPoint(0, 0),
      timestamp: map['timestamp'] as Timestamp? ?? Timestamp.now(),
    );
  }

  // ── Dart → Firestore ──────────────────────────────────────
  // Called when writing a new document to Firestore.
  // Note: `id` is NOT included — Firestore manages the doc ID separately.
  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'bloodType': bloodType,
      'location': location,
      'timestamp': timestamp,
    };
  }
}

// ============================================================
// FIRESTORE SERVICE — submitSOSRequest()
// Writes a new SOSRequest to the `emergencies` collection.
// Returns the new Firestore document ID on success.
// ============================================================
Future<String> submitSOSRequest({
  required String name,
  required String bloodType,
  required GeoPoint location,
}) async {
  final collection = FirebaseFirestore.instance.collection('emergencies');

  // `FieldValue.serverTimestamp()` lets Firestore set the timestamp
  // on the server, avoiding device clock skew across users.
  final docRef = await collection.add({
    'name': name,
    'bloodType': bloodType,
    'location': location,
    'timestamp': FieldValue.serverTimestamp(),
    'status': 'active', // useful for later — query only active requests
  });

  return docRef.id;
}

// ============================================================
// APP ROOT
// ============================================================
class DonorFinderApp extends StatelessWidget {
  const DonorFinderApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Local Donor Finder',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFC62828),
          brightness: Brightness.light,
          primary: const Color(0xFFC62828),
          onPrimary: Colors.white,
          surface: const Color(0xFFFFF8F8),
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFFC62828),
          foregroundColor: Colors.white,
          elevation: 0,
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFFC62828),
            foregroundColor: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(16),
            ),
          ),
        ),
        scaffoldBackgroundColor: const Color(0xFFFFF8F8),
      ),
      home: const MainShell(),
    );
  }
}

// ============================================================
// MAIN SHELL — BottomNavigationBar
// ============================================================
class MainShell extends StatefulWidget {
  const MainShell({super.key});

  @override
  State<MainShell> createState() => _MainShellState();
}

class _MainShellState extends State<MainShell> {
  int _selectedIndex = 0;

  static const List<Widget> _pages = [
    HomeScreen(),
    PostRequestScreen(),
    ProfileScreen(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _pages[_selectedIndex],
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _selectedIndex,
        onTap: (i) => setState(() => _selectedIndex = i),
        selectedItemColor: const Color(0xFFC62828),
        unselectedItemColor: Colors.grey[500],
        backgroundColor: Colors.white,
        type: BottomNavigationBarType.fixed,
        elevation: 8,
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.map_outlined),
            activeIcon: Icon(Icons.map),
            label: 'Map',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.edit_note_outlined),
            activeIcon: Icon(Icons.edit_note),
            label: 'Post Request',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.person_outline),
            activeIcon: Icon(Icons.person),
            label: 'Profile',
          ),
        ],
      ),
    );
  }
}

// ============================================================
// SCREEN 1 — HomeScreen
// Shows welcome card, SOS button, and live Firestore feed
// ============================================================
class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Donor Finder'),
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(24),
          child: Padding(
            padding: const EdgeInsets.only(left: 16, bottom: 10),
            child: Align(
              alignment: Alignment.centerLeft,
              child: Text(
                'Find help near you, instantly',
                style: Theme.of(context)
                    .textTheme
                    .bodySmall
                    ?.copyWith(color: Colors.white70),
              ),
            ),
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _WelcomeCard(),
            const SizedBox(height: 20),

            // SOS Button — opens the ModalBottomSheet
            _EmergencyButton(),
            const SizedBox(height: 28),

            // Live feed from Firestore
            Text('Recent SOS requests', style: _sectionLabelStyle()),
            const SizedBox(height: 10),

            // StreamBuilder listens to `emergencies` in real time.
            // Every time a new request is added, the UI updates automatically.
            StreamBuilder<QuerySnapshot>(
              stream: FirebaseFirestore.instance
                  .collection('emergencies')
                  .where('status', isEqualTo: 'active')
                  .orderBy('timestamp', descending: true)
                  .limit(10)
                  .snapshots(),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Center(
                    child: Padding(
                      padding: EdgeInsets.all(24),
                      child: CircularProgressIndicator(
                          color: Color(0xFFC62828)),
                    ),
                  );
                }

                if (snapshot.hasError) {
                  return Center(
                    child: Text(
                      'Error: ${snapshot.error}',
                      style: const TextStyle(color: Colors.red),
                    ),
                  );
                }

                final docs = snapshot.data?.docs ?? [];
                if (docs.isEmpty) return const _EmptyRequestsCard();

                return Column(
                  children: docs.map((doc) {
                    final request = SOSRequest.fromMap(
                      doc.id,
                      doc.data() as Map<String, dynamic>,
                    );
                    return _SOSRequestCard(request: request);
                  }).toList(),
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}

// ── Empty state when no Firestore requests exist ──────────────
class _EmptyRequestsCard extends StatelessWidget {
  const _EmptyRequestsCard();

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: const Border.fromBorderSide(
          BorderSide(color: Color(0xFFF5C4C4), width: 0.5),
        ),
      ),
      child: Column(
        children: [
          Icon(Icons.check_circle_outline, color: Colors.green[400], size: 36),
          const SizedBox(height: 8),
          Text(
            'No active SOS requests',
            style: TextStyle(color: Colors.grey[600], fontSize: 14),
          ),
        ],
      ),
    );
  }
}

// ── Card for a single live Firestore SOS request ─────────────
class _SOSRequestCard extends StatelessWidget {
  final SOSRequest request;
  const _SOSRequestCard({required this.request});

  @override
  Widget build(BuildContext context) {
    final time = request.timestamp.toDate();
    final timeStr =
        '${time.hour.toString().padLeft(2, '0')}:${time.minute.toString().padLeft(2, '0')}';

    return Card(
      elevation: 0,
      color: Colors.white,
      margin: const EdgeInsets.only(bottom: 10),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(14),
        side: const BorderSide(color: Color(0xFFF5C4C4), width: 0.5),
      ),
      child: Padding(
        padding: const EdgeInsets.all(14),
        child: Row(
          children: [
            CircleAvatar(
              backgroundColor: const Color(0xFFFFEBEE),
              radius: 22,
              child: Text(
                request.bloodType,
                style: const TextStyle(
                  color: Color(0xFFC62828),
                  fontWeight: FontWeight.w700,
                  fontSize: 12,
                ),
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    request.name,
                    style: const TextStyle(
                        fontWeight: FontWeight.w600, fontSize: 14),
                  ),
                  const SizedBox(height: 2),
                  Text(
                    'Posted at $timeStr',
                    style: TextStyle(fontSize: 12, color: Colors.grey[500]),
                  ),
                ],
              ),
            ),
            Container(
              padding:
                  const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
              decoration: BoxDecoration(
                color: const Color(0xFFFFEBEE),
                borderRadius: BorderRadius.circular(20),
              ),
              child: const Text(
                'ACTIVE',
                style: TextStyle(
                  color: Color(0xFFC62828),
                  fontSize: 10,
                  fontWeight: FontWeight.w700,
                  letterSpacing: 0.5,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ── Welcome card ──────────────────────────────────────────────
class _WelcomeCard extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 0,
      color: Colors.white,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
        side: const BorderSide(color: Color(0xFFF5C4C4), width: 0.5),
      ),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Row(
          children: [
            const CircleAvatar(
              radius: 24,
              backgroundColor: Color(0xFFFFEBEE),
              child: Text('🩸', style: TextStyle(fontSize: 20)),
            ),
            const SizedBox(width: 12),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // TODO: Replace with Firebase Auth user display name
                const Text(
                  'Good morning, Arjun',
                  style:
                      TextStyle(fontWeight: FontWeight.w500, fontSize: 15),
                ),
                const SizedBox(height: 2),
                Text(
                  'Hyderabad · Blood type A+',
                  style: TextStyle(fontSize: 12, color: Colors.grey[600]),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

// ── Big red emergency button — triggers the bottom sheet ──────
class _EmergencyButton extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: double.infinity,
      height: 130,
      child: ElevatedButton(
        onPressed: () => _showSOSBottomSheet(context),
        style: ElevatedButton.styleFrom(
          backgroundColor: const Color(0xFFC62828),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20),
          ),
        ),
        child: const Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.emergency, size: 36, color: Colors.white),
            SizedBox(height: 8),
            Text(
              'Request Emergency Help',
              style: TextStyle(
                  fontSize: 16,
                  fontWeight: FontWeight.w600,
                  color: Colors.white),
            ),
            SizedBox(height: 4),
            Text(
              'Tap to alert nearby donors',
              style: TextStyle(fontSize: 12, color: Colors.white70),
            ),
          ],
        ),
      ),
    );
  }
}

// ============================================================
// SOS BOTTOM SHEET
// Opened by the emergency button. Collects name + blood type
// and writes to Firestore via submitSOSRequest().
// ============================================================
void _showSOSBottomSheet(BuildContext context) {
  showModalBottomSheet(
    context: context,
    isScrollControlled: true, // sheet resizes when keyboard appears
    backgroundColor: Colors.transparent,
    builder: (_) => const _SOSBottomSheet(),
  );
}

class _SOSBottomSheet extends StatefulWidget {
  const _SOSBottomSheet();

  @override
  State<_SOSBottomSheet> createState() => _SOSBottomSheetState();
}

class _SOSBottomSheetState extends State<_SOSBottomSheet> {
  final _nameController = TextEditingController();
  String _selectedBloodType = 'A+';
  bool _isSubmitting = false;

  static const _bloodTypes = [
    'A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'
  ];

  @override
  void dispose() {
    _nameController.dispose(); // always dispose TextEditingControllers
    super.dispose();
  }

  // ── Validate → write to Firestore → close sheet ───────────
  Future<void> _submit() async {
    final name = _nameController.text.trim();

    if (name.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter your name')),
      );
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      // TODO: Replace this hardcoded GeoPoint with real GPS:
      //   final pos = await Geolocator.getCurrentPosition();
      //   final location = GeoPoint(pos.latitude, pos.longitude);
      const location = GeoPoint(17.3850, 78.4867); // Hyderabad placeholder

      await submitSOSRequest(
        name: name,
        bloodType: _selectedBloodType,
        location: location,
      );

      // Pop the sheet first, then show SnackBar on the parent scaffold
      if (mounted) Navigator.of(context).pop();

      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Row(
              children: [
                Icon(Icons.check_circle, color: Colors.white),
                SizedBox(width: 10),
                Text('SOS Posted Successfully!'),
              ],
            ),
            backgroundColor: Color(0xFFC62828),
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
    } catch (e) {
      // Common causes: no internet, Firestore security rules blocking the write
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to post SOS: $e'),
            backgroundColor: Colors.red[900],
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isSubmitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    // viewInsets.bottom = keyboard height; padding pushes sheet up
    final bottomInset = MediaQuery.of(context).viewInsets.bottom;

    return Container(
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      padding: EdgeInsets.fromLTRB(24, 20, 24, 24 + bottomInset),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Drag handle
          Center(
            child: Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: Colors.grey[300],
                borderRadius: BorderRadius.circular(4),
              ),
            ),
          ),
          const SizedBox(height: 20),

          const Text(
            'Post SOS Request',
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600),
          ),
          const SizedBox(height: 4),
          Text(
            'Nearby donors will be notified immediately.',
            style: TextStyle(fontSize: 13, color: Colors.grey[600]),
          ),
          const SizedBox(height: 24),

          // ── Name TextField ─────────────────────────────────
          const Text('Your name',
              style: TextStyle(fontSize: 13, fontWeight: FontWeight.w500)),
          const SizedBox(height: 8),
          TextField(
            controller: _nameController,
            textCapitalization: TextCapitalization.words,
            decoration: InputDecoration(
              hintText: 'e.g. Arjun Kumar',
              prefixIcon: const Icon(Icons.person_outline),
              filled: true,
              fillColor: const Color(0xFFFFF8F8),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Color(0xFFF5C4C4)),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Color(0xFFF5C4C4)),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide:
                    const BorderSide(color: Color(0xFFC62828), width: 1.5),
              ),
            ),
          ),
          const SizedBox(height: 18),

          // ── Blood Type Dropdown ────────────────────────────
          const Text('Blood type needed',
              style: TextStyle(fontSize: 13, fontWeight: FontWeight.w500)),
          const SizedBox(height: 8),
          DropdownButtonFormField<String>(
            value: _selectedBloodType,
            decoration: InputDecoration(
              prefixIcon: const Icon(Icons.water_drop_outlined,
                  color: Color(0xFFC62828)),
              filled: true,
              fillColor: const Color(0xFFFFF8F8),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Color(0xFFF5C4C4)),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Color(0xFFF5C4C4)),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide:
                    const BorderSide(color: Color(0xFFC62828), width: 1.5),
              ),
            ),
            items: _bloodTypes
                .map((bt) =>
                    DropdownMenuItem(value: bt, child: Text(bt)))
                .toList(),
            onChanged: (val) {
              if (val != null) setState(() => _selectedBloodType = val);
            },
          ),
          const SizedBox(height: 28),

          // ── Submit button (shows spinner while posting) ────
          SizedBox(
            width: double.infinity,
            height: 52,
            child: ElevatedButton(
              onPressed: _isSubmitting ? null : _submit,
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFFC62828),
                disabledBackgroundColor: Colors.red[200],
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(14),
                ),
              ),
              child: _isSubmitting
                  ? const SizedBox(
                      width: 22,
                      height: 22,
                      child: CircularProgressIndicator(
                        color: Colors.white,
                        strokeWidth: 2.5,
                      ),
                    )
                  : const Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(Icons.emergency, size: 20),
                        SizedBox(width: 8),
                        Text(
                          'Submit SOS',
                          style: TextStyle(
                              fontSize: 16, fontWeight: FontWeight.w600),
                        ),
                      ],
                    ),
            ),
          ),
        ],
      ),
    );
  }
}

// ============================================================
// SCREEN 2 — PostRequestScreen (detailed form tab)
// ============================================================
class PostRequestScreen extends StatelessWidget {
  const PostRequestScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Post a Request'),
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(24),
          child: Padding(
            padding: const EdgeInsets.only(left: 16, bottom: 10),
            child: Align(
              alignment: Alignment.centerLeft,
              child: Text(
                'Find donors in your area',
                style: Theme.of(context)
                    .textTheme
                    .bodySmall
                    ?.copyWith(color: Colors.white70),
              ),
            ),
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Blood type needed', style: _sectionLabelStyle()),
            const SizedBox(height: 10),
            _BloodTypeSelector(),
            const SizedBox(height: 20),
            Text('Hospital / location', style: _sectionLabelStyle()),
            const SizedBox(height: 8),
            const TextField(
              decoration: InputDecoration(
                hintText: 'e.g. NIMS Hospital, Punjagutta',
                prefixIcon: Icon(Icons.local_hospital_outlined),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.all(Radius.circular(12)),
                ),
              ),
            ),
            const SizedBox(height: 16),
            Text('Units required', style: _sectionLabelStyle()),
            const SizedBox(height: 8),
            const TextField(
              keyboardType: TextInputType.number,
              decoration: InputDecoration(
                hintText: 'e.g. 2',
                prefixIcon: Icon(Icons.water_drop_outlined),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.all(Radius.circular(12)),
                ),
              ),
            ),
            const SizedBox(height: 16),
            Text('Additional notes', style: _sectionLabelStyle()),
            const SizedBox(height: 8),
            const TextField(
              maxLines: 3,
              decoration: InputDecoration(
                hintText: 'Any other info for donors...',
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.all(Radius.circular(12)),
                ),
              ),
            ),
            const SizedBox(height: 28),
            SizedBox(
              width: double.infinity,
              height: 52,
              child: ElevatedButton(
                onPressed: () {},
                child: const Text(
                  'Post Request',
                  style: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _BloodTypeSelector extends StatefulWidget {
  @override
  State<_BloodTypeSelector> createState() => _BloodTypeSelectorState();
}

class _BloodTypeSelectorState extends State<_BloodTypeSelector> {
  String _selected = 'A+';
  final _types = ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'];

  @override
  Widget build(BuildContext context) {
    return Wrap(
      spacing: 8,
      runSpacing: 8,
      children: _types
          .map((t) => ChoiceChip(
                label: Text(t),
                selected: _selected == t,
                onSelected: (_) => setState(() => _selected = t),
                selectedColor: const Color(0xFFC62828),
                labelStyle: TextStyle(
                  color: _selected == t
                      ? Colors.white
                      : const Color(0xFFC62828),
                  fontWeight: FontWeight.w500,
                ),
                backgroundColor: const Color(0xFFFFEBEE),
                side: BorderSide.none,
              ))
          .toList(),
    );
  }
}

// ============================================================
// SCREEN 3 — ProfileScreen
// ============================================================
class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('My Profile')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          children: [
            const SizedBox(height: 12),
            const CircleAvatar(
              radius: 44,
              backgroundColor: Color(0xFFFFEBEE),
              child: Text('🩸', style: TextStyle(fontSize: 40)),
            ),
            const SizedBox(height: 12),
            const Text(
              'Arjun Kumar',
              style: TextStyle(fontSize: 20, fontWeight: FontWeight.w600),
            ),
            const SizedBox(height: 4),
            Text('arjun@example.com',
                style: TextStyle(fontSize: 13, color: Colors.grey[600])),
            const SizedBox(height: 24),
            _ProfileInfoRow(label: 'Blood Type', value: 'A+'),
            _ProfileInfoRow(label: 'City', value: 'Hyderabad'),
            _ProfileInfoRow(label: 'Total donations', value: '3'),
            _ProfileInfoRow(label: 'Last donated', value: '12 Jan 2026'),
            const SizedBox(height: 28),
            SizedBox(
              width: double.infinity,
              height: 50,
              child: OutlinedButton.icon(
                icon: const Icon(Icons.logout, size: 18),
                label: const Text('Sign Out'),
                style: OutlinedButton.styleFrom(
                  foregroundColor: const Color(0xFFC62828),
                  side: const BorderSide(color: Color(0xFFC62828)),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
                onPressed: () {
                  // TODO: FirebaseAuth.instance.signOut()
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _ProfileInfoRow extends StatelessWidget {
  final String label;
  final String value;
  const _ProfileInfoRow({required this.label, required this.value});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 10),
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: const Border.fromBorderSide(
          BorderSide(color: Color(0xFFF5C4C4), width: 0.5),
        ),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label,
              style: TextStyle(fontSize: 14, color: Colors.grey[700])),
          Text(value,
              style: const TextStyle(
                  fontSize: 14, fontWeight: FontWeight.w500)),
        ],
      ),
    );
  }
}

// ── Shared style for section labels ──────────────────────────
TextStyle _sectionLabelStyle() => const TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w500,
      color: Colors.grey,
      letterSpacing: 0.5,
    );